# Generated by Django 5.2.6 on 2025-09-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_news_produk'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='is_news_hot',
            field=models.BooleanField(default=False),
        ),
    ]
