# Generated by Django 5.2.6 on 2025-09-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_produk_is_news_hot'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='product_views',
            field=models.IntegerField(default=0),
        ),
    ]
