# Generated by Django 5.2.6 on 2025-09-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_produk_product_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produk',
            old_name='product_views',
            new_name='products_views',
        ),
    ]
