# Generated by Django 5.2.6 on 2025-09-15 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_product_views_produk_products_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produk',
            name='is_news_hot',
        ),
    ]
