# Generated by Django 5.2.7 on 2025-11-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_produk_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='category',
            field=models.CharField(choices=[('boots', 'Boots'), ('knee_guards', 'Knee_guards'), ('footballs', 'Footballs'), ('socks', 'Socks'), ('shirts', 'Shirts'), ('gloves', 'Gloves')], default='boots', max_length=20),
        ),
    ]
